<?php

/**
 * @file
 * The ITG Common module.
 *
 * Provides common functionality and customizations.
 *
 */



/**
 * Function for debugging arrays and objects.
 * @param $arg
 *   array or object to be printed.
 */
function p($arg) {
    print '<pre>';
    print_r($arg);
    die;
}

function pr($arg) {
    print '<pre>';
    print_r($arg);
    print '</pre>';
}

/**
 * Implements hook_form_alter().
 */
function itg_common_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_register_form') {
    
    //Add cancel button to user edit form and redirects to user manage page on click of cancel button.
    $destination = 'manage-users';
    $form['actions']['cancel'] = array(
        '#markup' => l(t('Cancel'), $destination),
        '#weight' => 20,
    );
  }
}

