<?php
/**
 * @file
 * syndication_feature.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function syndication_feature_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance:
  // 'field_collection_item-field_syndication_ftp_details-field_syndication_ftp_name'.
  $field_instances['field_collection_item-field_syndication_ftp_details-field_syndication_ftp_name'] = array(
    'bundle' => 'field_syndication_ftp_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_ftp_name',
    'label' => 'FTP Name',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 1,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_syndication_ftp_details-field_syndication_ftp_password'.
  $field_instances['field_collection_item-field_syndication_ftp_details-field_syndication_ftp_password'] = array(
    'bundle' => 'field_syndication_ftp_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_ftp_password',
    'label' => 'FTP Password',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 4,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_syndication_ftp_details-field_syndication_ftp_url'.
  $field_instances['field_collection_item-field_syndication_ftp_details-field_syndication_ftp_url'] = array(
    'bundle' => 'field_syndication_ftp_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_ftp_url',
    'label' => 'FTP URL',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_syndication_ftp_details-field_syndication_ftp_username'.
  $field_instances['field_collection_item-field_syndication_ftp_details-field_syndication_ftp_username'] = array(
    'bundle' => 'field_syndication_ftp_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_ftp_username',
    'label' => 'FTP Username',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 3,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_syndication_rule_details-field_syndication_content_type'.
  $field_instances['field_collection_item-field_syndication_rule_details-field_syndication_content_type'] = array(
    'bundle' => 'field_syndication_rule_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Select Content Type',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 8,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_content_type',
    'label' => 'Select Content Type',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 1,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_syndication_rule_details-field_syndication_feed_type'.
  $field_instances['field_collection_item-field_syndication_rule_details-field_syndication_feed_type'] = array(
    'bundle' => 'field_syndication_rule_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Select Feed type',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 6,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_feed_type',
    'label' => 'Select Feed type',
    'required' => 1,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 3,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_syndication_rule_details-field_syndication_frequency'.
  $field_instances['field_collection_item-field_syndication_rule_details-field_syndication_frequency'] = array(
    'bundle' => 'field_syndication_rule_details',
    'default_value' => array(
      0 => array(
        'value' => 'Daily',
      ),
    ),
    'deleted' => 0,
    'description' => 'Select Frequency',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_frequency',
    'label' => 'Select Frequency',
    'required' => 1,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 0,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_syndication_rule_details-field_syndication_mode'.
  $field_instances['field_collection_item-field_syndication_rule_details-field_syndication_mode'] = array(
    'bundle' => 'field_syndication_rule_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Select Delivery End Point',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 7,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_mode',
    'label' => 'Select Delivery End Point',
    'required' => 1,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 4,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_syndication_rule_details-field_syndication_num_of_feeds'.
  $field_instances['field_collection_item-field_syndication_rule_details-field_syndication_num_of_feeds'] = array(
    'bundle' => 'field_syndication_rule_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Number of feeds',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => '',
        ),
        'type' => 'number_integer',
        'weight' => 9,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_num_of_feeds',
    'label' => 'Number of feeds',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 8,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_syndication_rule_details-field_syndication_select_section'.
  $field_instances['field_collection_item-field_syndication_rule_details-field_syndication_select_section'] = array(
    'bundle' => 'field_syndication_rule_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Select Section',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_plain',
        'weight' => 5,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_select_section',
    'label' => 'Select Section',
    'required' => 1,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 2,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_syndication_rule_details-field_syndication_set_day'.
  $field_instances['field_collection_item-field_syndication_rule_details-field_syndication_set_day'] = array(
    'bundle' => 'field_syndication_rule_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Set Day',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_set_day',
    'label' => 'Set Day',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 5,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_syndication_rule_details-field_syndication_set_day_month'.
  $field_instances['field_collection_item-field_syndication_rule_details-field_syndication_set_day_month'] = array(
    'bundle' => 'field_syndication_rule_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Set Date',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_set_day_month',
    'label' => 'Set Date',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 6,
    ),
  );

  // Exported field_instance:
  // 'field_collection_item-field_syndication_rule_details-field_syndication_time'.
  $field_instances['field_collection_item-field_syndication_rule_details-field_syndication_time'] = array(
    'bundle' => 'field_syndication_rule_details',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Set Time "Time should be 24 hr format."',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_time',
    'label' => 'Set Time',
    'required' => 1,
    'settings' => array(
      'exclude_cv' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'node-syndication_client-field_email_address'.
  $field_instances['node-syndication_client-field_email_address'] = array(
    'bundle' => 'syndication_client',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'exclude_cv' => 0,
    'field_name' => 'field_email_address',
    'label' => 'Via Mail',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 7,
    ),
  );

  // Exported field_instance:
  // 'node-syndication_client-field_service_fetch_link'.
  $field_instances['node-syndication_client-field_service_fetch_link'] = array(
    'bundle' => 'syndication_client',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'exclude_cv' => 0,
    'field_name' => 'field_service_fetch_link',
    'label' => 'Via Web URL',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'node-syndication_client-field_story_expiry_date'.
  $field_instances['node-syndication_client-field_story_expiry_date'] = array(
    'bundle' => 'syndication_client',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'date',
        'settings' => array(
          'format_type' => 'itg_date_formate',
          'fromto' => '',
          'multiple_from' => '',
          'multiple_number' => '',
          'multiple_to' => '',
          'show_remaining_days' => 0,
        ),
        'type' => 'date_default',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'exclude_cv' => 0,
    'field_name' => 'field_story_expiry_date',
    'label' => 'Expiry On',
    'required' => 0,
    'settings' => array(
      'default_value' => 'blank',
      'default_value2' => 'same',
      'default_value_code' => '',
      'default_value_code2' => '',
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'date',
      'settings' => array(
        'display_all_day' => 0,
        'increment' => 1,
        'input_format' => 'd/m/Y - H:i:s',
        'input_format_custom' => '',
        'label_position' => 'above',
        'no_fieldset' => 0,
        'text_parts' => array(),
        'year_range' => '-3:+3',
      ),
      'type' => 'date_popup',
      'weight' => 8,
    ),
  );

  // Exported field_instance:
  // 'node-syndication_client-field_syndication_client_title'.
  $field_instances['node-syndication_client-field_syndication_client_title'] = array(
    'bundle' => 'syndication_client',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Client Title',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'taxonomy',
        'settings' => array(),
        'type' => 'taxonomy_term_reference_plain',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_client_title',
    'label' => 'Client Title',
    'required' => 1,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 0,
    ),
  );

  // Exported field_instance:
  // 'node-syndication_client-field_syndication_delivery_mode'.
  $field_instances['node-syndication_client-field_syndication_delivery_mode'] = array(
    'bundle' => 'syndication_client',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Select Delivery Mode',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_delivery_mode',
    'label' => 'Select Delivery Mode',
    'required' => 1,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_buttons',
      'weight' => 2,
    ),
  );

  // Exported field_instance:
  // 'node-syndication_client-field_syndication_ftp_details'.
  $field_instances['node-syndication_client-field_syndication_ftp_details'] = array(
    'bundle' => 'syndication_client',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'field_collection',
        'settings' => array(
          'add' => 'Add',
          'delete' => 'Delete',
          'description' => TRUE,
          'edit' => 'Edit',
          'view_mode' => 'full',
        ),
        'type' => 'field_collection_view',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_ftp_details',
    'label' => 'Via FTP',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'field_collection',
      'settings' => array(),
      'type' => 'field_collection_embed',
      'weight' => 3,
    ),
  );

  // Exported field_instance:
  // 'node-syndication_feed_from_pattern-field_syndication_feed_clients'.
  $field_instances['node-syndication_feed_from_pattern-field_syndication_feed_clients'] = array(
    'bundle' => 'syndication_feed_from_pattern',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Client Title',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_feed_clients',
    'label' => 'Client Title',
    'required' => 1,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 1,
    ),
  );

  // Exported field_instance:
  // 'node-syndication_feed_from_pattern-field_syndication_feed_content'.
  $field_instances['node-syndication_feed_from_pattern-field_syndication_feed_content'] = array(
    'bundle' => 'syndication_feed_from_pattern',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Syndication feed content',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_feed_content',
    'label' => 'Syndication feed content',
    'required' => 1,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 2,
    ),
  );

  // Exported field_instance:
  // 'node-syndication_feed_from_pattern-field_syndication_feed_type'.
  $field_instances['node-syndication_feed_from_pattern-field_syndication_feed_type'] = array(
    'bundle' => 'syndication_feed_from_pattern',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Select Feed type',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_feed_type',
    'label' => 'Select Feed type',
    'required' => 1,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 3,
    ),
  );

  // Exported field_instance:
  // 'node-syndication_feed_from_pattern-field_syndication_footer'.
  $field_instances['node-syndication_feed_from_pattern-field_syndication_footer'] = array(
    'bundle' => 'syndication_feed_from_pattern',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_footer',
    'label' => 'Footer',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 32,
    ),
  );

  // Exported field_instance:
  // 'node-syndication_feed_from_pattern-field_syndication_header'.
  $field_instances['node-syndication_feed_from_pattern-field_syndication_header'] = array(
    'bundle' => 'syndication_feed_from_pattern',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_header',
    'label' => 'Header',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 31,
    ),
  );

  // Exported field_instance:
  // 'node-syndication_feed_from_pattern-field_syndication_xml_formate'.
  $field_instances['node-syndication_feed_from_pattern-field_syndication_xml_formate'] = array(
    'bundle' => 'syndication_feed_from_pattern',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'xml_field',
        'settings' => array(),
        'type' => 'xml_field_safe',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_xml_formate',
    'label' => 'Xml format',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
      'validation_callback' => 'xml_field_is_valid_xml_string',
      'xml_example_collapsed' => 1,
      'xml_example_show' => 1,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'xml_field_codemirror',
      'settings' => array(
        'codemirror' => array(
          'theme' => 'default',
        ),
      ),
      'type' => 'xml_field_codemirror',
      'weight' => 4,
    ),
  );

  // Exported field_instance:
  // 'node-syndication_rule-field_syndication_rule_details'.
  $field_instances['node-syndication_rule-field_syndication_rule_details'] = array(
    'bundle' => 'syndication_rule',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'field_collection',
        'settings' => array(
          'add' => 'Add',
          'delete' => 'Delete',
          'description' => TRUE,
          'edit' => 'Edit',
          'view_mode' => 'full',
        ),
        'type' => 'field_collection_view',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_rule_details',
    'label' => 'Syndication rule details',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'field_collection',
      'settings' => array(),
      'type' => 'field_collection_embed',
      'weight' => 2,
    ),
  );

  // Exported field_instance:
  // 'node-syndication_rule-field_syndication_rule_title'.
  $field_instances['node-syndication_rule-field_syndication_rule_title'] = array(
    'bundle' => 'syndication_rule',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Select Client title',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'exclude_cv' => 0,
    'field_name' => 'field_syndication_rule_title',
    'label' => 'Select Client title',
    'required' => 0,
    'settings' => array(
      'exclude_cv' => FALSE,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 1,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Client Title');
  t('Expiry On');
  t('FTP Name');
  t('FTP Password');
  t('FTP URL');
  t('FTP Username');
  t('Footer');
  t('Header');
  t('Number of feeds');
  t('Select Client title');
  t('Select Content Type');
  t('Select Delivery End Point');
  t('Select Delivery Mode');
  t('Select Feed type');
  t('Select Frequency');
  t('Select Section');
  t('Set Date');
  t('Set Day');
  t('Set Time');
  t('Set Time "Time should be 24 hr format."');
  t('Syndication feed content');
  t('Syndication rule details');
  t('Via FTP');
  t('Via Mail');
  t('Via Web URL');
  t('Xml format');

  return $field_instances;
}
