<select onchange="redirectToConstituencyPage(this.value)">
<option value="0" selected="selected">Constituency results</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/nippani-result">Nippani</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/chikkodi-sadalga-result">Chikkodi-Sadalga</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/athani-result">Athani</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kagwad-result">Kagwad</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kudachi-result">Kudachi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/raybag-result">Raybag</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/hukkeri-result">Hukkeri</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/arabhavi-result">Arabhavi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/gokak-result">Gokak</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/yemkanmardi-result">Yemkanmardi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/belgaum-uttar-result">Belgaum Uttar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/belgaum-dakshin-result">Belgaum Dakshin</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/belgaum-rural-result">Belgaum Rural</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/khanapur-result">Khanapur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kittur-result">Kittur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/bailhongal-result">Bailhongal</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/saundatti-yellamma-result">Saundatti Yellamma</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/ramdurg-result">Ramdurg</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/mudhol-result">Mudhol</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/terdal-result">Terdal</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/jamkhandi-result">Jamkhandi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/bilgi-result">Bilgi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/badami-result">Badami</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/bagalkot-result">Bagalkot</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/hungund-result">Hungund</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/muddebihal-result">Muddebihal</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/devar-hippargi-result">Devar Hippargi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/basavana-bagevadi-result">Basavana Bagevadi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/babaleshwar-result">Babaleshwar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/bijapur-city-result">Bijapur City</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/nagthan-result">Nagthan</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/indi-result">Indi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/sindgi-result">Sindgi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/afzalpur-result">Afzalpur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/jevargi-result">Jevargi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/shorapur-result">Shorapur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/shahapur-result">Shahapur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/yadgir-result">Yadgir</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/gurmitkal-result">Gurmitkal</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/chittapur-result">Chittapur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/sedam-result">Sedam</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/chincholi-result">Chincholi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/gulbarga-rural-result">Gulbarga Rural</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/gulbarga-dakshin-result">Gulbarga Dakshin</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/gulbarga-uttar-result">Gulbarga Uttar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/aland-result">Aland</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/basavakalyan-result">Basavakalyan</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/humnabad-result">Humnabad</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/bidar-south-result">Bidar South</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/bidar-result">Bidar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/bhalki-result">Bhalki</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/aurad-result">Aurad</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/raichur-rural-result">Raichur Rural</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/raichur-result">Raichur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/manvi-result">Manvi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/devadurga-result">Devadurga</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/lingsugur-result">Lingsugur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/sindhanur-result">Sindhanur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/maski-result">Maski</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kushtagi-result">Kushtagi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kanakagiri-result">Kanakagiri</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/gangawati-result">Gangawati</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/yelburga-result">Yelburga</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/koppal-result">Koppal</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/shirahatti-result">Shirahatti</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/gadag-result">Gadag</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/ron-result">Ron</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/naragund-result">Naragund</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/navalgund-result">Navalgund</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kundgol-result">Kundgol</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/dharwad-result">Dharwad</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/hubli-dharwad-east-result">Hubli-Dharwad East</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/hubli-dharwad-central-result">Hubli-Dharwad Central</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/hubli-dharwad-west-result">Hubli-Dharwad West</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kalaghatagi-result">Kalaghatagi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/haliyal-result">Haliyal</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/karwar-result">Karwar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kumta-result">Kumta</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/bhatkal-result">Bhatkal</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/sirsi-result">Sirsi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/yellapur-result">Yellapur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/hanagal-result">Hanagal</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/shiggaon-result">Shiggaon</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/haveri-result">Haveri(S.C)</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/byadgi-result">Byadgi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/hirekerur-result">Hirekerur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/ranebennur-result">Ranebennur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/hadagali-result">Hadagali(Sc)</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/hagaribommanahalli-result">Hagaribommanahalli(S.C.)</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/vijayanagara-result">Vijayanagara</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kampli-result">Kampli</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/siruguppa-result">Siruguppa(S.T)</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/ballari-rural--result">Ballari Rural (St)</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/bellary-city-result">Bellary City</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/sandur-result">Sandur(St)</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kudligi-result">Kudligi(St)</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/molakalmuru-result">Molakalmuru</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/challakere-result">Challakere</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/chitradurga-result">Chitradurga</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/hiriyur-result">Hiriyur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/hosadurga-result">Hosadurga</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/holalkere-result">Holalkere(S.C)</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/jagalur-result">Jagalur(St)</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/harapanahalli-result">Harapanahalli</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/harihar-result">Harihar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/davanagere-north-result">Davanagere North</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/davanagere-south-result">Davanagere South</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/mayakonda-result">Mayakonda</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/channagiri-result">Channagiri</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/honnali-result">Honnali</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/shimoga-rural-result">Shimoga Rural</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/bhadravathi-result">Bhadravathi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/shimoga-result">Shimoga</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/tirthahalli-result">Tirthahalli</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/shikaripura-result">Shikaripura</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/sorab-result">Sorab</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/sagar-result">Sagar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/byndoor-result">Byndoor</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kundapura-result">Kundapura</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/udupi-result">Udupi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kaup-result">Kaup</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/karkala-result">Karkala</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/sringeri-result">Sringeri</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/mudigere-result">Mudigere</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/chickamagalur-result">Chickamagalur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/tarikere-result">Tarikere</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kadur-result">Kadur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/chikkanayakana-result">Chikkanayakana</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/tiptur-result">Tiptur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/turuvekere-result">Turuvekere</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kunigal-result">Kunigal</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/tumkur-city-result">Tumkur City</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/tumkur-rural-result">Tumkur Rural</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/koratagere-result">Koratagere</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/gubbi-result">Gubbi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/sira-result">Sira</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/pavagada-result">Pavagada</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/madhugiri-result">Madhugiri</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/gauribidanur-result">Gauribidanur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/bagepalli-result">Bagepalli</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/chikkaballapur-result">Chikkaballapur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/shidlaghatta-result">Shidlaghatta</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/chintamani-result">Chintamani</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/srinivasapur-result">Srinivasapur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/mulbagal-result">Mulbagal</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kolar-gold-field-result">Kolar Gold Field</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/bangarpet-result">Bangarpet</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kolar-result">Kolar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/malur-result">Malur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/yelahanka-result">Yelahanka</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/krpura-result">K.R.Pura</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/byatarayanapura-result">Byatarayanapura</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/yeshvanthapura-result">Yeshvanthapura</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/rajarajeshwarinagar-result">Rajarajeshwarinagar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/dasarahalli-result">Dasarahalli</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/mahalakshmi-layout-result">Mahalakshmi Layout</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/malleshwaram-result">Malleshwaram</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/hebbal-result">Hebbal</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/pulakeshinagar-result">Pulakeshinagar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/sarvagnanagar-result">Sarvagnanagar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/cv-raman-nagar-result">C.V. Raman Nagar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/shivajinagar-result">Shivajinagar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/shanti-nagar-result">Shanti Nagar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/gandhi-nagar-result">Gandhi Nagar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/rajaji-nagar-result">Rajaji Nagar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/govindraj-nagar-result">Govindraj Nagar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/vijay-nagar-result">Vijay Nagar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/chamrajpet-result">Chamrajpet</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/chickpet-result">Chickpet</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/basavanagudi-result">Basavanagudi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/padmanaba-nagar-result">Padmanaba Nagar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/btmlayout-result">B.T.M.Layout</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/jayanagar-result">Jayanagar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/mahadevapura-result">Mahadevapura</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/bommanahalli-result">Bommanahalli</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/bangalore-south-result">Bangalore South</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/anekal-result">Anekal</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/hosakote-result">Hosakote</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/devanahalli-result">Devanahalli</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/doddaballapur-result">Doddaballapur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/nelamangala-result">Nelamangala</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/magadi-result">Magadi</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/ramanagaram-result">Ramanagaram</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kanakapura-result">Kanakapura</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/channapatna-result">Channapatna</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/malavalli-result">Malavalli</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/maddur-result">Maddur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/melukote-result">Melukote</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/mandya-result">Mandya</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/shrirangapattana-result">Shrirangapattana</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/nagamangala-result">Nagamangala</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/krishnarajapete-result">Krishnarajapete</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/shravanabelagola-result">Shravanabelagola</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/arsikere-result">Arsikere</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/belur-result">Belur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/hassan-result">Hassan</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/holenarasipur-result">Holenarasipur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/arkalgud-result">Arkalgud</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/sakleshpur-result">Sakleshpur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/belthangady-result">Belthangady</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/moodabidri-result">Moodabidri</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/mangalore-city-north-result">Mangalore City North</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/mangalore-city-south-result">Mangalore City South</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/mangalore-result">Mangalore</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/bantval-result">Bantval</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/puttur-result">Puttur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/sullia-result">Sullia</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/madikeri-result">Madikeri</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/virajpet-result">Virajpet</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/periyapatna-result">Periyapatna</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/krishnarajanagara-result">Krishnarajanagara</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/hunasuru-result">Hunasuru</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/heggadadevankote-result">Heggadadevankote</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/nanjangud-result">Nanjangud</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/chamundeshwari-result">Chamundeshwari</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/krishnaraja-result">Krishnaraja</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/chamaraja-result">Chamaraja</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/narasimharaja-result">Narasimharaja</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/varuna-result">Varuna</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/tnarasipur-result">T.Narasipur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/hanur-result">Hanur</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/kollegal-result">Kollegal</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/chamarajanagar-result">Chamarajanagar</option>
<option value="<?php echo FRONT_URL;?>/elections/karnataka-election-2018/constituency/gundlupet-result">Gundlupet</option>
</select>
<script>
function redirectToConstituencyPage(args){
  if(args != 0 && args != '' && args !== undefined){
    window.open(args,'_blank');
  }
}
</script>