<?php

/**
 * @file
 * The ITG Syndication clients.
 * Contains functionality for ITG Syndication for clients.
 */

/**
 * Implements hook_menu().
 */
function itg_syndication_clients_menu() {
  $items['bsb/story/%'] = array(
    'page callback' => 'itg_bsb_story_syndication',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'file' => 'inc/itg_bsb_story.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * This function is used to create bsb directory on public folder
 * hook_install
 */
function itg_syndication_clients_install() {
  $bsbdir = 'public://bsb';
  file_prepare_directory($bsbdir, FILE_CREATE_DIRECTORY);
}

function slugify($text) {
  $text = preg_replace('&', 'and', $text);
  $text = preg_replace('~[^\pL\d]+~u', '-', $text);
  $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);
  $text = preg_replace('~[^-\w]+~', '', $text);
  $text = trim($text, '-');
  $text = preg_replace('~-+~', '-', $text);
  $text = strtolower($text);
  if (empty($text)) {
    return 'n-a';
  }
  return $text;
}


function get_terms_name_by_ids($tids = array()){
  if(count($tids) <= 0)
    return FALSE;
  
  $query = db_select('taxonomy_term_data', 'ttd');
  $query->fields('ttd', array('tid', 'name'));
  $query->condition('ttd.tid', $tids, 'IN');
  $result = $query->execute()->fetchAll(PDO::FETCH_ASSOC);
  return $result;
}