<?php

/**
 * @file
 * The ITG Syndication clients for store configuration
 */
function getbsb_client_array() {
  $story = array(
    '1206533' => 'it-story-movies.xml',
    '1206550' => 'it-story-sports.xml',
    '1206567' => 'it-story-lifestyle.xml',
    '1206574' => 'it-story-business.xml',
    '1206577' => 'it-story-world.xml',
    '1206578' => 'it-story-india.xml',
    '1206676' => 'it-story-cricket.xml',
    '1206687' => 'it-story-topstories.xml',
    '1206719' => 'it-story-elections.xml',
    '1206793' => 'it-story-foodanddrink.xml',
    '1206796' => 'it-story-television.xml',
    '1207046' => 'it-story-gossip.xml',
    '1207051' => 'it-story-north.xml',
    '1207536' => 'it-story-ipl-2013.xml',
    '1207645' => 'it-story-diary.xml',
    '1207665' => 'it-story-ground-report.xml',
    '1207666' => 'it-story-highlights.xml',
    '1207667' => 'it-story-more-stories.xml',
    '1207715' => 'it-story-mobile-main.xml',
    '1208001' => 'it-story-news.xml',
    '1208185' => 'it-story-uttar-pradesh.xml',
    '1208365' => 'it-story-gujarat.xml',
    '1208366' => 'it-story-karnataka.xml',
    '1208367' => 'it-story-tamilnadu.xml',
    '1208368' => 'it-story-maharashtra.xml',
    '1208369' => 'it-story-westbengal.xml',
  );
  return $story;
}
