<?php

/**
 * Get file name from fid
 * @param type $audioFid
 */
function itg_astro_file_name($audio_fid) {
  $itg_query = db_select('file_managed', 'f');
  $itg_query->condition('fid', $audio_fid, '=')
      ->fields('f', array('filename'));

  $itg_result = $itg_query->execute()->fetchField();
  if ($itg_result != '') {
    return $itg_result;
  }

  return '';
}

/**
 * Load zodiac thumbnail for astro content type
 * @return type
 */
function itg_astro_zodiac_thumbnail() {
  $itg_vid = taxonomy_vocabulary_machine_name_load('zodiac_sign');
  $itg_term = taxonomy_get_tree($itg_vid->vid, 0, NULL, TRUE);

  return $itg_term;
}

/**
 * Implements hook_form_alter().
 * @param type $form
 * @param type $form_state
 * @param type $form_id
 */
function itg_astro_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'astro_node_form') {
    $form['#attached']['js'] = array(
      drupal_get_path('module', 'itg_astro') . '/js/itg_astro.js',
      drupal_get_path('module', 'itg_astro') . '/js/moment.js',
      drupal_get_path('module', 'itg_astro') . '/js/jquery.validate.min.js',
    );
    if ($form['nid']['#value'] == NULL) {
      $form['title']['#default_value'] = date('M jS Y');
    }
    $form['#action'] = '?destination=manage-astro';
    $form['actions']['submit']['#submit'][] = 'itg_astro_change_message';    
    $form['#after_build'][] = 'itg_astro_after_build';
    unset($form['field_numerology']['und']['#options']['_none']);
    unset($form['field_astro_frequency2']['und']['#options']['_none']);
  }
}

/**
 * after build function for altering field collection label.
 */
function itg_astro_after_build($form, &$form_state) {
  // Change Zodiac field item label name and add * on mandotory fields      
  for ($i = 0; $i <= 11; $i++) {
    if ($i == 0) {
      $form['field_astro_numerology_values']['und'][$i]['field_story_source_id']['und'][0]['value']['#title'] = t('Number') . '<span class="form-required" title="This field is required."> *</span>';
      $form['field_astro_numerology_values']['und'][$i]['field_buzz_description']['und'][0]['value']['#title'] = t('Enter Text') . '<span class="form-required" title="This field is required."> *</span>';
    }

    $form['field_astro_zodiac']['und'][$i]['field_buzz_description']['und'][0]['value']['#title'] = t('Text') . '<span class="form-required" title="This field is required."> *</span>';
    $form['field_astro_zodiac']['und'][$i]['field_zodiac_sign']['und']['#title'] = t('Zodiac Sign') . '<span class="form-required" title="This field is required."> *</span>';
  }

  // Add cancel button to create/edit astro page
  $form['actions']['cancel'] = array(
    '#markup' => l(t('Cancel'), 'manage-astro', array('attributes' => array('class' => 'button'))),
    '#weight' => 20,
  );

  // Send variable to itg_astro.js file
  global $user, $base_url;
  unset($form['metatags']['intro_text']['#markup']);
  unset($form['metatags']['#description']);

  $settings = array();
  $settings['uid'] = $user->uid;
  $settings['base_url'] = $base_url;
  $settings['type'] = 'astro';
  $settings['nid'] = $form['nid']['#value'];
  drupal_add_js(array('uid' => $settings), 'setting');

  return $form;
}

/**
 * Function return name of the sunsign.
 */
function itg_astro_sunsign_name($index) {
  $name = array(
    'Aries',
    'Taurus',
    'Gemini',
    'Cancer',
    'Leo',
    'Virgo',
    'Libra',
    'Scorpio',
    'Sagittarius',
    'Capricorn',
    'Aquarius',
    'Pisces',
  );
  if ($index <= 11) {
    return $name[$index];
  }

  return '';
}

/**
 * Custom submit callback function to change message after astro node save.
 * @param type $form
 * @param type $form_state
 */
function itg_astro_change_message($form, &$form_state) {
  $messages = drupal_get_messages('status');
  drupal_set_message(t('Astro has been successfully filled.'));
}

/**
 * Implements hook_block_info().
 */
function itg_astro_block_info() {
  $blocks['astro_tab_form_block'] = array(
    'info' => t('Astro Form Tab Block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view()
 * @param type $delta
 */
function itg_astro_block_view($delta = '') {
  global $user;
  $block = array();
  $data = '';
  switch ($delta) {
    case 'astro_tab_form_block':
      $block['content'] = theme('astro_tab_form_display_block', array('data' => $data));
      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 * @param type $existing
 * @param type $type
 * @param type $theme
 * @param type $path
 */
function itg_astro_theme($existing, $type, $theme, $path) {
  $themes = array(
    'astro_tab_form_display_block' => array(
      'template' => 'astro-form-tab-template',
      'path' => drupal_get_path('module', 'itg_astro') . '/templates',
      'variables' => array('data' => NULL),
    ),
    'astro_node_form' => array(
      'arguments' => array('form' => NULL),
      'template' => 'astro-node-form',
      'path' => drupal_get_path('module', 'itg_astro') . '/templates',
      'render element' => 'form',
    ),
  );

  return $themes;
}

/**
 * Implements hook_field_widget_form_alter()
 * @staticvar int $count
 * @param type $element
 * @param type $form_state
 * @param type $context
 */
function itg_astro_field_widget_form_alter(&$element, &$form_state, $context) {
  if (isset($element['#field_name']) && $element['#field_name'] == 'field_zodiac_sign') {
    static $count = 0;
    $itg_thumb = itg_astro_zodiac_thumbnail();
    $itg_img_uri = $itg_thumb[$count]->field_astro_thumb_icon['und'][0]['uri'];
    $element['#suffix'] = '<img src="' . image_style_url("thumbnail", $itg_img_uri) . '" alt="' . $itg_thumb[$count]->field_astro_thumb_icon['und'][0]['alt'] . '" title="' . $itg_thumb[$count]->field_astro_thumb_icon['und'][0]['title'] . '">';
    $element['#default_value'] = $itg_thumb[$count]->tid;
    ++$count;
  }
}

/**
 * Implements hook_menu-alter()
 * @param array $item
 */
function itg_astro_menu_alter(&$item) {
  // Hide the "Create new account" tab
  $item['user/login']['type'] = MENU_CALLBACK;
}
