<Root>
<content>
<type>live_stream_IT</type>
<iphone>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/indiatoday_app.smil/playlist.m3u8
</iphone>
<ipad>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/indiatoday_app.smil/playlist.m3u8
</ipad>
<android>http://feeds.intoday.in/hltapps/api/livetv.php</android>
<playbook>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/indiatoday_app.smil/playlist.m3u8
</playbook>
<bb>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/indiatoday_app.smil/playlist.m3u8
</bb>
<mp4sream>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/indiatoday_app.smil/manifest
</mp4sream>
<wp7>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/indiatoday_app.smil/manifest
</wp7>
<live_stream_IT>http://m.indiatoday.in/hlt/indiatodaystream.html</live_stream_IT>
<channels>
<channel>
<name>India Today</name>
<icon>http://media2.intoday.in/app/logo/IT_90X90.png</icon>
<ios>
<video_link>
<autoplay>1</autoplay>
<isnative>1</isnative>
<preroll>1</preroll>
<signed>1</signed>
<native>
<!--
 for signed = 1 we must and should have have the signed_feed  
-->
<signed_feed>
http://feeds.intoday.in/indiatoday/livetv/it_signed.xml?type=xml
</signed_feed>
<unsigned_url>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/indiatoday_app.smil/playlist.m3u8
</unsigned_url>
</native>
<embed>
http://feeds.intoday.in/indiatoday/livetv/indiatodayembed.html
</embed>
</video_link>
<audio_link>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/it_150k/playlist.m3u8?wowzaaudioonly
</audio_link>
</ios>
<android>
<video_link>
<autoplay>1</autoplay>
<isnative>1</isnative>
<preroll>1</preroll>
<signed>1</signed>
<native>
<!--
 instead of .php file we can have a xml feed which will contains the signed url (.m3u8 along with time stamp). and this feed containing signed url will updated in certain time interval. Thus we can skip the php click and enhance user experience, as well we can implement the same in ios too  
-->
<!--
 for signed = 1 we must and should have have the signed_feed  
-->
<signed_feed>
http://feeds.intoday.in/indiatoday/livetv/it_signed.xml?type=xml
</signed_feed>
<unsigned_url>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/indiatoday_app.smil/playlist.m3u8
</unsigned_url>
</native>
<embed>
http://feeds.intoday.in/indiatoday/livetv/indiatodayembed.html
</embed>
</video_link>
<audio_link>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/it_150k/playlist.m3u8?wowzaaudioonly
</audio_link>
</android>
</channel>
<channel>
<name>Aaj Tak</name>
<icon>http://media2.intoday.in/app/logo/AT_90X90.png</icon>
<ios>
<video_link>
<autoplay>1</autoplay>
<isnative>0</isnative>
<preroll>1</preroll>
<signed>0</signed>
<native>
<signed_feed>
http://feeds.intoday.in/aajtak/api/at_signed.xml?type=xml
</signed_feed>
<unsigned_url>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/aajtak_app.smil/playlist.m3u8
</unsigned_url>
</native>
<embed>
http://feeds.intoday.in/aajtak/api/aajtakembed.html
</embed>
</video_link>
<audio_link>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/aajtak_150k/playlist.m3u8?wowzaaudioonly
</audio_link>
</ios>
<android>
<video_link>
<autoplay>1</autoplay>
<isnative>1</isnative>
<preroll>1</preroll>
<signed>1</signed>
<native>
<!--  http://feeds.intoday.in/aajtak/api/livetv.php  -->
<!--
 for signed = 0 we must and should have have the unsigned url  
-->
<signed_feed>
http://feeds.intoday.in/aajtak/api/at_signed.xml?type=xml
</signed_feed>
<unsigned_url>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/aajtak_app.smil/playlist.m3u8
</unsigned_url>
</native>
<embed>
http://feeds.intoday.in/aajtak/api/aajtakembed.html
</embed>
</video_link>
<audio_link>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/aajtak_150k/playlist.m3u8?wowzaaudioonly
</audio_link>
</android>
</channel>
<channel>
<name>Delhi Aaj Tak</name>
<icon>
http://media2.intoday.in/app/logo/delhi_AT_90X90.png
</icon>
<ios>
<video_link>
<autoplay>1</autoplay>
<isnative>0</isnative>
<preroll>1</preroll>
<signed>0</signed>
<native>
<signed_feed>
http://feeds.intoday.in/aajtak/api/at_signed.xml?type=xml
</signed_feed>
<unsigned_url>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/aajtak_app.smil/playlist.m3u8
</unsigned_url>
</native>
<embed>
http://feeds.intoday.in/aajtak/api/delhiaajtakembed.html
</embed>
</video_link>
<audio_link>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/aajtak_150k/playlist.m3u8?wowzaaudioonly
</audio_link>
</ios>
<android>
<video_link>
<autoplay>1</autoplay>
<isnative>0</isnative>
<preroll>1</preroll>
<signed>0</signed>
<native>
<!--  http://feeds.intoday.in/aajtak/api/livetv.php  -->
<!--
 for signed = 0 we must and should have have the unsigned url  
-->
<signed_feed>
http://feeds.intoday.in/aajtak/api/at_signed.xml?type=xml
</signed_feed>
<unsigned_url>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/aajtak_app.smil/playlist.m3u8
</unsigned_url>
</native>
<embed>
http://feeds.intoday.in/aajtak/api/delhiaajtakembed.html
</embed>
</video_link>
<audio_link>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/aajtak_150k/playlist.m3u8?wowzaaudioonly
</audio_link>
</android>
</channel>
<channel>
<name>Tez</name>
<icon>http://media2.intoday.in/app/logo/tez_90X90.png</icon>
<ios>
<video_link>
<autoplay>1</autoplay>
<isnative>0</isnative>
<preroll>1</preroll>
<signed>0</signed>
<native>
<signed_feed>
http://feeds.intoday.in/aajtak/api/at_signed.xml?type=xml
</signed_feed>
<unsigned_url>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/aajtak_app.smil/playlist.m3u8
</unsigned_url>
</native>
<embed>http://feeds.intoday.in/aajtak/api/tezembed.html</embed>
</video_link>
<audio_link>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/aajtak_150k/playlist.m3u8?wowzaaudioonly
</audio_link>
</ios>
<android>
<video_link>
<autoplay>1</autoplay>
<isnative>0</isnative>
<preroll>1</preroll>
<signed>0</signed>
<native>
<!--  http://feeds.intoday.in/aajtak/api/livetv.php  -->
<!--
 for signed = 0 we must and should have have the unsigned url  
-->
<signed_feed>
http://feeds.intoday.in/aajtak/api/at_signed.xml?type=xml
</signed_feed>
<unsigned_url>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/aajtak_app.smil/playlist.m3u8
</unsigned_url>
</native>
<embed>http://feeds.intoday.in/aajtak/api/tezembed.html</embed>
</video_link>
<audio_link>
http://lmil.live-s.cdn.bitgravity.com/cdn-live/_definst_/lmil/live/aajtak_150k/playlist.m3u8?wowzaaudioonly
</audio_link>
</android>
</channel>
</channels>
</content>
</Root>
