<?php

/**
 * @file
 * ITG Event backend module.
 *
 * Provides customizations and functions for Event Backend.
 *
 */

/**
 * Implementation of hook_form_alter().
 * @param array $form 
 * @param array reference $form_state
 * @param string $form_id
 * @return array $form
 */
function itg_event_backend_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "event_backend_node_form") {

    $form['#after_build'][] = 'itg_event_backend_after_build';
    //$form['#validate'][] = 'itg_event_backend_node_form_validate';
    array_unshift($form['#validate'], "itg_event_backend_node_form_validate");
    $form['actions']['cancel'] = array(
      '#markup' => l(t('Cancel'), 'manage-event-backend', array('attributes' => array('class' => 'button'))),
      '#weight' => 20,
    );
    // Node redirection code
    if (isset($form_state['storage']['step']) && ($form_state['storage']['step'] == 'step_configuration' || $form_state['storage']['step'] == 'step_program_schedule' || $form_state['storage']['step'] == 'step_sponsor' || $form_state['storage']['step'] == 'step_media' || $form_state['storage']['step'] == 'step_highlights')) {
      // $form['#submit'][] = 'custom_node_submit';
      $form['actions']['submit']['#submit'][] = 'itg_event_backend_configuration_redirect';
    }
    // Current step save in session variable
    if (isset($form_state['storage']['step'])) {
      $_SESSION['current_step'] = $form_state['storage']['step'];
    }
  }
  if ($form_id == 'sponsor_node_form') {
    $form['#after_build'][] = 'itg_event_backend_sponsor';
    $form['actions']['cancel'] = array(
      '#markup' => l(t('Cancel'), 'manage-sponsor', array('attributes' => array('class' => 'button'))),
      '#weight' => 20,
    );
  }
}

/**
 * Implements custom validate for event backend.
 * @param array $form
 * @param array $form_state
 */
function itg_event_backend_node_form_validate($form, &$form_state) {
  $startdate = strtotime($form_state['values']['field_event_start_date'][LANGUAGE_NONE][0]['value']);
  $enddate = strtotime($form_state['values']['field_event_close_date'][LANGUAGE_NONE][0]['value']);
  $registration_close = strtotime($form_state['values']['field_registration_close_date'][LANGUAGE_NONE][0]['value']);
  $registration_start = strtotime($form_state['values']['field_story_expiry_date'][LANGUAGE_NONE][0]['value']);
//  if ($registration_close < $registration_start) {
//    form_set_error('field_story_expiry_date', 'Registration start date must be less then registration close date.');
//  }
  if ($enddate < $startdate) {
    form_set_error('field_event_close_date', 'Close date must be greater then start date.');
  }
//  if ($registration_close > $enddate) {
//    form_set_error('field_registration_close_date', 'Registration close date must be less then event close date.');
//  }

  $event_type = $form_state['values']['field_event_type'][LANGUAGE_NONE][0]['value'];
  if ($event_type == 'paid' && $form_state['values']['field_group_registration_fee_5'][LANGUAGE_NONE][0]['value'] == '') {
    form_set_error('field_group_registration_fee_5', 'Group Registration Fee (upto 5) is required.');
  }

  if ($event_type == 'paid' && $form_state['values']['field_group_registration_fee_10'][LANGUAGE_NONE][0]['value'] == '') {
    form_set_error('field_group_registration_fee_10', 'Group Registration Fee (upto 10) is required.');
  }

  if ($event_type == 'paid' && $form_state['values']['field_individual_registration_fe'][LANGUAGE_NONE][0]['value'] == '') {
    form_set_error('field_individual_registration_fe', 'Individual Registration Fee is required.');
  }
  // Fees validation for registration
  if ($event_type == 'paid' && $form_state['values']['field_individual_registration_fe'][LANGUAGE_NONE][0]['value'] > $form_state['values']['field_group_registration_fee_5'][LANGUAGE_NONE][0]['value']) {
    form_set_error('field_individual_registration_fe', 'Individual Registration Fee should be less then Group Registration Fee (upto 5)');
  }
   if ($event_type == 'paid' && $form_state['values']['field_group_registration_fee_5'][LANGUAGE_NONE][0]['value'] > $form_state['values']['field_group_registration_fee_10'][LANGUAGE_NONE][0]['value']) {
    form_set_error('field_group_registration_fee_5', 'Group Registration Fee (upto 5) should be less then Group Registration Fee (upto 10).');
  }
   if (($event_type == 'paid' || $event_type == 'free') && $form_state['values']['field_no_of_tickets'][LANGUAGE_NONE][0]['value'] == '') {
    form_set_error('field_no_of_tickets', 'Please enter No. of Tickets');
  }
}

/**
 * After build for sponsor form.
 * @param array $form
 * @param array $form_state
 * @return array $form
 */
function itg_event_backend_sponsor($form, &$form_state) {
  drupal_add_js(drupal_get_path('module', 'itg_event_backend') . '/js/itg_event_sponsor.js', array('weight' => 3));
  global $user, $base_url;
  unset($form['metatags']['intro_text']['#markup']);
  $form['path']['pathauto']['#title'] = t('Generate automatic Sef URL');
  unset($form['metatags']['intro_text']['#markup']);
  unset($form['metatags']['#description']);
  $settings = array();
  $settings['base_url'] = $base_url;
  $settings['uid'] = $user->uid;
  drupal_add_js(array('itg_event_sponsor' => array('settings' => $settings)), array('type' => 'setting'));
  $form['title']['#title'] = 'Sponsor Title';
  return $form;
}

/**
 * After build for Event backend form.
 * @param array $form
 * @param array $form_state
 * @return array $form
 */
function itg_event_backend_after_build($form, &$form_state) {
  if (arg(0) == 'node' && is_numeric(arg(1)) && arg(2) == "edit") {
    if ($form['#node']->status == 1) {
      drupal_add_js('jQuery(document).ready(function(){ jQuery("#edit-field-event-start-date-und-0-value-datepicker-popup-1").attr("disabled", "disabled")});', array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));
      drupal_add_js('jQuery(document).ready(function(){ jQuery("#edit-field-event-close-date-und-0-value-datepicker-popup-1").attr("disabled", "disabled")});', array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));
      drupal_add_js('jQuery(document).ready(function(){ jQuery("#edit-field-story-expiry-date-und-0-value-datepicker-popup-1").attr("disabled", "disabled")});', array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));
    }
  }
  drupal_add_js(drupal_get_path('module', 'itg_event_backend') . '/js/itg_event_backend.js', array('weight' => 3));
  if (isset($form_state['values']['nid'])) {
    $settings = array();
    $settings['base_url'] = $base_url;
    $settings['node_id'] = $form_state['values']['nid'];
    drupal_add_js(array('itg_event_backend_nid' => array('settings' => $settings)), array('type' => 'setting'));
  }
  global $user, $base_url;
  unset($form['metatags']['intro_text']['#markup']);
  $form['path']['pathauto']['#title'] = t('Generate automatic Sef URL');
  unset($form['metatags']['intro_text']['#markup']);
  unset($form['metatags']['#description']);
  $settings = array();
  $settings['base_url'] = $base_url;
  $settings['uid'] = $user->uid;
  drupal_add_js(array('itg_event_backend' => array('settings' => $settings)), array('type' => 'setting'));

  $endDate = strtotime('+1 day', strtotime($form_state['values']['field_event_close_date'][LANGUAGE_NONE][0]['value']));
  $startDate = $form_state['values']['field_event_start_date'][LANGUAGE_NONE][0]['value'];
  $endDate_new = date('Y-m-d', $endDate);
  $startDate_new = explode(' ', $startDate);
  $options_daywise = itg_event_backend_date_interval($startDate_new[0], $endDate_new);
  $highlight_options = array('_none' => t('- Select Daywise -'));
  $media_options = array('_none' => t('- Select Daywise -'));
  foreach ($form['field_program_schedule'][LANGUAGE_NONE] as $key => $program) {
    if (is_numeric($key)) {
      $program_daywise = $form['field_program_schedule'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#entity']->field_daywise_event[LANGUAGE_NONE][0]['value'];
      $program_title = $form['field_program_schedule'][LANGUAGE_NONE][$key]['#entity']->field_story_expert_name[LANGUAGE_NONE][0]['value'];
      $start_time = date('H:i', strtotime($form['field_program_schedule'][LANGUAGE_NONE][$key]['#entity']->field_start_time[LANGUAGE_NONE][0]['value']));
      $end_time = date('H:i', strtotime($form['field_program_schedule'][LANGUAGE_NONE][$key]['#entity']->field_start_time[LANGUAGE_NONE][0]['value2']));
      $day_value = explode(':', $program_daywise);
      $highlight_options[$program_daywise.'--'.$program_title.'--'.$start_time.'--'.$end_time] = t($day_value[0].' - '.$program_title.' - '.$start_time.' to '.$end_time);
      $media_options[$program_daywise] = t($program_daywise);
      // p($form['field_program_schedule'][LANGUAGE_NONE][$key]);
      if (isset($form['field_program_schedule'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#entity']->field_daywise_event[LANGUAGE_NONE][0]['value'])) {
        $form['field_program_schedule'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#value'][0] = $form['field_program_schedule'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#entity']->field_daywise_event[LANGUAGE_NONE][0]['value'];
        $form['field_program_schedule'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#default_value'][0] = $form['field_program_schedule'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#entity']->field_daywise_event[LANGUAGE_NONE][0]['value'];
      }
      unset($form['field_program_schedule'][LANGUAGE_NONE][$key]['field_daywise_event']['#validated']);
      $form['field_program_schedule'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#options'] = $options_daywise;
    }
  }

//event hightlights
  foreach ($form['field_event_highlights'][LANGUAGE_NONE] as $key => $program) {
    if (is_numeric($key)) {
      if (isset($form['field_event_highlights'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#entity']->field_daywise_event[LANGUAGE_NONE][0]['value'])) {
        $form['field_event_highlights'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#value'][0] = $form['field_event_highlights'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#entity']->field_daywise_event[LANGUAGE_NONE][0]['value'];
        $form['field_event_highlights'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#default_value'][0] = $form['field_event_highlights'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#entity']->field_daywise_event[LANGUAGE_NONE][0]['value'];
      }
      if (isset($form['field_event_highlights'][LANGUAGE_NONE][$key]['field_programe_title'][LANGUAGE_NONE]['#entity']->field_programe_title[LANGUAGE_NONE][0]['value'])) {
        $form['field_event_highlights'][LANGUAGE_NONE][$key]['field_programe_title'][LANGUAGE_NONE]['#value'][0] = $form['field_event_highlights'][LANGUAGE_NONE][$key]['field_programe_title'][LANGUAGE_NONE]['#entity']->field_programe_title[LANGUAGE_NONE][0]['value'];
        $form['field_event_highlights'][LANGUAGE_NONE][$key]['field_programe_title'][LANGUAGE_NONE]['#default_value'][0] = $form['field_event_highlights'][LANGUAGE_NONE][$key]['field_programe_title'][LANGUAGE_NONE]['#entity']->field_programe_title[LANGUAGE_NONE][0]['value'];
      }

      $form['field_event_highlights'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#options'] = $options_daywise;
      $form['field_event_highlights'][LANGUAGE_NONE][$key]['field_programe_title'][LANGUAGE_NONE]['#options'] = $highlight_options;
      
      $form['field_event_highlights'][LANGUAGE_NONE][$key]['field_daywise_event']['#validated'] = TRUE;
//      unset($form['field_event_highlights'][LANGUAGE_NONE][$key]['field_programe_title']['#validated']);
    }
  }
//event media
  foreach ($form['field_event_media'][LANGUAGE_NONE] as $key => $program) {
    if (is_numeric($key)) {
      if (isset($form['field_event_media'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#entity']->field_daywise_event[LANGUAGE_NONE][0]['value'])) {
        $form['field_event_media'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#value'][0] = $form['field_event_media'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#entity']->field_daywise_event[LANGUAGE_NONE][0]['value'];
        $form['field_event_media'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#default_value'][0] = $form['field_event_media'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#entity']->field_daywise_event[LANGUAGE_NONE][0]['value'];
      }

      $form['field_event_media'][LANGUAGE_NONE][$key]['field_daywise_event'][LANGUAGE_NONE]['#options'] = $media_options;
      $form['field_event_media'][LANGUAGE_NONE][$key]['field_daywise_event']['#validated'] = TRUE;
    }
  }
  //Next and Save button access according steps
  if (isset($form_state['storage']['step']) && ($form_state['storage']['step'] == 'step_first' || $form_state['storage']['step'] == 'step_second' || $form_state['storage']['step'] == 'step_program_schedule')) {
    $form['actions']['submit']['#access'] = FALSE;
    $form['actions']['preview']['#access'] = FALSE;
    $form['actions']['delete']['#access'] = FALSE;
  }
  if (isset($form_state['storage']['step']) && ($form_state['storage']['step'] == 'step_program_schedule' || $form_state['storage']['step'] == 'step_sponsor' || $form_state['storage']['step'] == 'step_media' || $form_state['storage']['step'] == 'step_highlights')) {
    $form['actions']['submit']['#access'] = TRUE;
    $form['actions']['submit']['#value'] = 'Next';
    $form['actions']['next']['#access'] = FALSE;
    if (isset($form['actions']['delete'])) {
      $form['actions']['delete']['#access'] = FALSE;
    }
  }


  $form['title']['#title'] = 'Event Title';
  $form['field_group_registration_fee_5']['#states'] = array(
    'visible' => array(
      ':input[name="field_event_type[und]"]' => array('value' => 'paid'),
    ),
    'required' => array(
      ':input[name="field_event_type[und]"]' => array('value' => 'paid'),
    ),
  );
  $form['field_group_registration_fee_10']['#states'] = array(
    'visible' => array(
      ':input[name="field_event_type[und]"]' => array('value' => 'paid'),
    ),
    'required' => array(
      ':input[name="field_event_type[und]"]' => array('value' => 'paid'),
    ),
  );
  $form['field_individual_registration_fe']['#states'] = array(
    'visible' => array(
      ':input[name="field_event_type[und]"]' => array('value' => 'paid'),
    ),
    'required' => array(
      ':input[name="field_event_type[und]"]' => array('value' => 'paid'),
    ),
  );
  $form['field_no_of_tickets']['#states'] = array(
    'visible' => array(
      array(':input[name="field_event_type[und]"]' => array('value' => 'paid')),
      'OR',
      array(':input[name="field_event_type[und]"]' => array('value' => 'free')),
    ),
    'required' => array(
      array(':input[name="field_event_type[und]"]' => array('value' => 'paid')),
      'OR',
      array(':input[name="field_event_type[und]"]' => array('value' => 'free')),
    ),
  );

  return $form;
}

/**
 * Implements custom submit for redirect
 * @param array $form
 * @param array $form_state
 */
function itg_event_backend_configuration_redirect($form, &$form_state) {
  if (isset($_GET['destination'])) {
    unset($_GET['destination']);
  }
  if (isset($form_state['storage']['step']) && ($form_state['storage']['step'] == 'step_configuration')) {


    $form_state['redirect'] = 'manage-event-backend';
  }
  elseif (isset($form_state['storage']['step']) && ($form_state['storage']['step'] == 'step_sponsor')) {
    drupal_get_messages();
    $form_state['redirect'] = array('node/' . $form_state['values']['nid'] . '/edit', array('query' => array('step' => 'step_highlights')));
  }
  elseif (isset($form_state['storage']['step']) && ($form_state['storage']['step'] == 'step_media')) {
    drupal_get_messages();
    $form_state['redirect'] = array('node/' . $form_state['values']['nid'] . '/edit', array('query' => array('step' => 'step_configuration')));
  }
  elseif (isset($form_state['storage']['step']) && ($form_state['storage']['step'] == 'step_highlights')) {
    drupal_get_messages();
    $form_state['redirect'] = array('node/' . $form_state['values']['nid'] . '/edit', array('query' => array('step' => 'step_media')));
  }
  else {
    drupal_get_messages();
    $form_state['redirect'] = array('node/' . $form_state['values']['nid'] . '/edit', array('query' => array('step' => 'step_sponsor')));
  }
}

/**
 * Imlements function for dynamic options.
 * @param string $startDate the start of the date range
 * @param string $endDate the end of the date range
 * @param string $format DateTime format, default is Y-m-d
 * @return array returns every date between $startDate and $endDate, formatted as "Y-m-d"
 */
function itg_event_backend_date_interval($startDate, $endDate, $format = "d-m-Y") {
  $begin = new DateTime($startDate);
  $end = new DateTime($endDate);
  $interval = new DateInterval('P1D'); // 1 Day
  $dateRange = new DatePeriod($begin, $interval, $end);

  $range = [];
  $range = array('_none' => t('- Select Daywise -'));
  $i = 1;
  foreach ($dateRange as $date) {
    $range['Day-' . $i . ':' . $date->format($format)] = t('Day-' . $i . ':' . $date->format($format));
    $i++;
  }

  return $range;
}

/**
 * Implements hook_theme().
 * {@inheritdoc}
 */
function itg_event_backend_theme($existing, $type, $theme, $path) {
  $themes = array(
    'itg_event_backend_tab_form_display_block' => array(
      'template' => 'itg-event-backend-form-tab-template',
      'path' => drupal_get_path('module', 'itg_event_backend') . '/templates',
      'variables' => array('data' => NULL),
    ),
    'sponsor_node_form' => array(
      'arguments' => array('form' => NULL),
      'template' => 'sponsor-node-form',
      'path' => drupal_get_path('module', 'itg_event_backend') . '/templates',
      'render element' => 'form',
    ),
    'itg_event_sponsor_tab_form_display_block' => array(
      'template' => 'itg-event-backend-form-sponsor-tab-template',
      'path' => drupal_get_path('module', 'itg_event_backend') . '/templates',
      'variables' => array('data' => NULL),
    ),
  );
  return $themes;
}

/**
 * Implements hook_block_info().
 * {@inheritdoc}
 */
function itg_event_backend_block_info() {
  $blocks['event_backend_tab_form_block'] = array(
    'info' => t('event backend Form Tab Block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  $blocks['sponsor_tab_form_block'] = array(
    'info' => t('sponsor Form Tab Block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 * {@inheritdoc}
 */
function itg_event_backend_block_view($delta = '') {
  global $user;
  $block = array();
  $data = '';
  switch ($delta) {
    case 'event_backend_tab_form_block':
      $block['content'] = theme('itg_event_backend_tab_form_display_block', array('data' => $data));
      break;
    case 'sponsor_tab_form_block':
      $block['content'] = theme('itg_event_sponsor_tab_form_display_block', array('data' => $data));
      break;
  }

  return $block;
}

/**
 * Implements hook_views_pre_render() 
 * {@inheritdoc}
 */
function itg_event_backend_views_pre_render(&$view) {
  if ($view->name == "Event_backend" && $view->current_display == 'page') {
    global $user;
    $event_content = '';
    $event_content = l(t('Create Event'), 'node/add/event-backend');
    $view->attachment_before = $event_content;
  }
  if ($view->name == "Sponsor" && $view->current_display == 'page') {
    global $user;
    $sponsor_content = '';
    $sponsor_content = l(t('Create Sponsor'), 'node/add/sponsor', array('query' => array('destination' => 'manage-sponsor')));
    $view->attachment_before = $sponsor_content;
  }
}

/**
 * Implement hook_form_FORM_ID_alter().
 * @param array $form
 * @param array $form_state
 * @param string $form_id
 */
function itg_event_backend_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  //Get the Form Id
  if ($form["#id"] == 'views-exposed-form-Event-backend-page') {
    $form['title']['#autocomplete_path'] = 'content-title-list/event_backend/autocomplete';
    $form['title']['#attributes'] = array('placeholder' => t('Title'));
  }
  if ($form["#id"] == 'views-exposed-form-Sponsor-page') {
    $form['title']['#autocomplete_path'] = 'content-title-list/sponsor/autocomplete';
    $form['title']['#attributes'] = array('placeholder' => t('Title'));
  }
}

/**
 * Implements hook_menu().
 * {@inheritdoc}
 */
function itg_event_backend_menu() {
  $items = array();
  $items['event-publish'] = array(
    'page callback' => 'itg_event_backend_publish_event',
    'access arguments' => array('access content'),
    'file' => 'includes/itg_event_backend.inc',
    'type' => MENU_CALLBACK,
  );
  $items['event-unpublish'] = array(
    'page callback' => 'itg_event_backend_unpublish_event',
    'access arguments' => array('access content'),
    'file' => 'includes/itg_event_backend.inc',
    'type' => MENU_CALLBACK,
  );
  $items['event-title/%'] = array(
    'page callback' => 'itg_event_backend_title_event',
    'access arguments' => array('access content'),
    'file' => 'includes/itg_event_backend.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}
