<?php

/**
 * Implements hook_menu().
 */
function itg_fia_menu() {
  // Implementing the menu item for itg_fia.
  $items['itg_fia.xml'] = array(
    'title' => 'Taxonomy Comments',
    'description' => 'list fia data',
    'page callback' => 'itg_fia_data',
    'access callback' => TRUE,
    'page arguments' => array('itg_fia_data'),
    'file' => 'include/itg_fia.inc',
  );
  $items['admin/structure/itg_fia_config'] = array(
    'title' => 'ITG FIA Configuration',
    'description' => 'Add your appid',
    'page callback' => 'drupal_get_form',
    'access callback' => 'user_access',
    'page arguments' => array('itg_fia_config_form'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'include/itg_fia.inc',
    'weight' => 100,
  );

  return $items;
}


/**
 * Implements hook_html_head_alter().
 */
function itg_fia_html_head_alter(&$head_elements) {
  $fia_pagesid = variable_get('itg_fia_config', '');
  if (!empty($fia_pagesid)) {
    $head_elements['fia_pagesid'] = array(
      '#type' => 'html_tag',
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'fb:pages',
        'content' => $fia_pagesid
      ),
    );
  }
}

/**
 * Implements hook_uninstall().
 */
function itg_fia_uninstall() {
  // Delete variables.
  variable_del('itg_fia_config');
}

/**
 * Function for adding ad code in fbia
 * @param string $content
 * @param type $after_word1
 * @return string
 */
function itg_fia_split_by_words($content, $after_word1 = 200) {
  // Insert at the end of the paragraph every 300 words
  //$after_word1 = 300;
  $len = strlen($content);
  $i = 0;
  // Keep adding untill end of content or $max_ads number of ads has ben inserted
  while ($i < $len) {
    // Work our way untill the apropriate length
    $word_cout = 0;
    $in_tag = false;
    while (++$i < $len && $word_cout < $after_word1) {
      if (!$in_tag && ctype_space($content[$i])) {
        // Whitespace
        $word_cout++;
      }
      else if (!$in_tag && $content[$i] == '<') {
        // Begin tag
        $in_tag = true;
        $word_cout++;
      }
      else if ($in_tag && $content[$i] == '>') {
        // End tag
        $in_tag = false;
      }
    }

    // Find the next '</p>'
    $i = strpos($content, "</p>", $i);
    if ($i === false) {
      // No more paragraph endings
      break;
    }
    else {
      // Add the length of </p>
      $i += 4;
      $ad = "<figure class='op-ad'> <iframe width='300' height='250' style='border:0; margin:0;' src='https://www.facebook.com/adnw_request?placement=1634971070080984_1635110376733720&adtype=banner300x250'></iframe></figure>";
      $content = substr($content, 0, $i) . $ad . substr($content, $i);

      // Set the correct i
      $i+= strlen($ad);
    }
  }
  return $content;
}
