<?php

module_load_include('inc', 'itg_analytics', 'includes/itg_analytics_helper');

/**
 * @file
 * Main functionality for itg analytics module.
 */

/**
 * Implements hook_menu().
 * {@inheritdoc}
 */
function itg_analytics_menu() {
  $items = array();
  $items['itg-update-analytics-node-count-data'] = array(
    'page callback' => 'itg_update_analytics_node_count_data',
    'type' => MENU_CALLBACK,
    'file' => 'includes/itg-analytics-main.inc',
    'access arguments' => array('administer itg analytics widget'),
  );
  return $items;
}

/**
 * Implements hook_cronapi().
 * {@inheritdoc}
 */
function itg_analytics_cronapi($op, $job = NULL) {
  $items['itg-update-analytics-node-count-data'] = array(
    'description' => 'This cron is responsible for updating analytics data , which is used for sotring in widgets',
    'callback' => 'itg_update_analytics_node_count_data',
    'file' => 'includes/itg-analytics-main.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 * {@inheritdoc}
 */
function itg_analytics_permission() {
  return array(
    'administer itg analytics widget' => array(
      'title' => t('administer itg analytics widget'),
      'description' => t('administer administer itg analytics widget permission'),
    ),
  );
}

/**
 * Implements hook_views_api().
 * {@inheritdoc}
 */
function itg_analytics_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'itg_analytics') . '/includes/views',
  );
}
