<?php
/**
 * @file
 * Install, update and uninstall functions for the ITG Category Manager module.
 */

/**
 * Implements hook_uninstall().
 */
function itg_category_manager_uninstall() {
  variable_del('itg_category_manager_types');
  variable_del('itg_category_manager_case_sensitive');
}

/**
 * Clear menu cache to match new configuration place
 */
function itg_category_manager_update_7001() {
  cache_clear_all(NULL, 'cache_menu');
}
